### ISSUE TITLE
Error when training on MPII dataset

### ISSUE THREAD

**Issue by alex-razor** [leoxiaobin/deep-high-resolution-net.pytorch#100]
I managed to run inference on several images successfully.

However, when i am trying to train again on MPII data using the example command line:
```
python tools/train.py \
    --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml \
```

I get the following error:
```
Traceback (most recent call last):
  File "/hdd/deep-high-resolution-net.pytorch/tools/train.py", line 223, in <module>
    main()
  File "/hdd/deep-high-resolution-net.pytorch/tools/train.py", line 111, in main
    writer_dict['writer'].add_graph(model, (dump_input, ))
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/tensorboardX/writer.py", line 738, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 240, in graph
    trace = torch.jit.trace(model, args)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 772, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 898, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 669, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1881, in __init__
    self._modules[name] = TracedModule(submodule, id_set)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1881, in __init__
    self._modules[name] = TracedModule(submodule, id_set)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1881, in __init__
    self._modules[name] = TracedModule(submodule, id_set)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1881, in __init__
    self._modules[name] = TracedModule(submodule, id_set)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1881, in __init__
    self._modules[name] = TracedModule(submodule, id_set)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/hdd/deep-high-resolution-net.pytorch/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1855, in __init__
    assert(isinstance(orig, torch.nn.Module))
AssertionError
```

**Comment by ahanahaner** [comment]
I have the same problem as you. Have you solved it？

**Comment by tomahawk810** [comment]
Same problem here.

**Comment by TeeboneTing** [comment]
same problem

**Comment by TeeboneTing** [comment]
Reference: #98 by downgrade tesorboardX version to 1.6 and all works well.

**Comment by dzyjjpy** [comment]
which pytorch version do you use? I downgrade tesorboardX version to 1.6, another issue occured as below:  @TeeboneTing @leoxiaobin 

=> init weights from normal distribution
=> loading pretrained model models/pytorch/imagenet/hrnet_w32-36af842e.pth
Traceback (most recent call last):
  File "tools/train.py", line 223, in <module>
    main()
  File "tools/train.py", line 111, in main
    writer_dict['writer'].add_graph(model, (dump_input, ))
  File "/home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/tensorboardX/writer.py", line 566, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 235, in graph
    _optimize_trace(trace, torch.onnx.utils.OperatorExportTypes.ONNX)
  File "/home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 175, in _optimize_trace
    trace.set_graph(_optimize_graph(trace.graph(), operator_export_type))
  File "/home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 201, in _optimize_graph
    torch._C._jit_pass_lower_all_tuples(graph)
RuntimeError: kind_.is_prim() INTERNAL ASSERT FAILED at /pytorch/torch/csrc/jit/ir.cpp:904, please report a bug to PyTorch. Only prim ops are allowed to not have a registered operator but aten::_convolution doesn't have one either. We don't know if this op has side effects. (hasSideEffects at /pytorch/torch/csrc/jit/ir.cpp:904)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fd2f6c54273 in /home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: torch::jit::Node::hasSideEffects() const + 0x2d5 (0x7fd215f162c5 in /home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x3ca9923 (0x7fd215f7c923 in /home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x3ca9a75 (0x7fd215f7ca75 in /home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #4: torch::jit::EliminateDeadCode(torch::jit::Block*, bool, torch::jit::DCESideEffectPolicy) + 0x138 (0x7fd215f798d8 in /home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #5: torch::jit::LowerAllTuples(std::shared_ptr<torch::jit::Graph>&) + 0x29 (0x7fd215f9c3f9 in /home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x454cbb (0x7fd2fbcd0cbb in /home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x1d3ef4 (0x7fd2fba4fef4 in /home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: python() [0x50746c]
<omitting python frames>
frame #10: python() [0x5057d7]
frame #11: python() [0x506ac3]
frame #12: python() [0x507330]
frame #14: python() [0x5057d7]
frame #15: python() [0x506ac3]
frame #16: python() [0x507330]
frame #18: python() [0x5057d7]
frame #19: python() [0x506ac3]
frame #20: python() [0x507330]
frame #22: python() [0x504e80]
frame #23: python() [0x506ac3]
frame #24: python() [0x507330]
frame #26: python() [0x5064e4]
frame #27: python() [0x507330]
frame #29: python() [0x504e80]
frame #31: python() [0x646a12]
frame #36: __libc_start_main + 0xf0 (0x7fd300ee6830 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by dzyjjpy** [comment]
I use pytorch==1.2 torchvision==0.4,  Does anyone have similar experience?
no problem when running "python tools/test.py", in coco/mpii

**Comment by dzyjjpy** [comment]
it works when torch==1.0, tensorboardX==1.6

**Comment by TeeboneTing** [comment]
@dzyjjpy 
My version:
torch==1.0.0 
torchvision==0.1.6
tensorboardX==1.6

**Comment by eng100200** [comment]
@dzyjjpy hello, can i ask you one issue?

**Comment by GZP123** [comment]
Thank your issue. 
My version: 
pytorch == 1.2.0, 
torchvision == 0.4.0, 
tensorbloardx = 1.6. 
It works, but other bugs comes. 😂

**Comment by dzyjjpy** [comment]
@TeeboneTing thanks. @eng100200 pls describe your issue.

**Comment by eng100200** [comment]
@GZP123  have you run the test code on mpii for w32?

**Comment by GZP123** [comment]
> @GZP123 have you run the test code on mpii for w32?

I do not. I have the similar bug with @dzyjjpy 😂 . And I can not run, let me try to so it more.

**Comment by GZP123** [comment]
> @GZP123 have you run the test code on mpii for w32?

Now, my version is:
pytorch == 1.0.1,
torchvision == 0.2.1,
tensorboardx = 1.6. 
And I can run the train code. For the test code, I want to wait some days.

**Comment by eng100200** [comment]
@dzyjjpy hello, i want to ask  few questions;
1. Why we flipped images in testing the mpii dataset?
2. I think mpii provide bounding box, but, i am not sure. However, how did you get the bounding boxes for mpii and how you computed center and scale?
3. Further, the validation set of mpii used for testing do you single person detection or multi-person detection?
4. how can i display images after i detect the pose points, i mean disply with pose points?
5. how can i test any image of my own?

**Comment by eng100200** [comment]
@GZP123 did you train using mpii?

**Comment by GZP123** [comment]
> @GZP123 did you train using mpii?
I do it and the speed is enough. But I can not train for MS COCO, because of my GPUs. I have ubuntu 16.0 and 2 GTX 1080 GPUs. Maybe I need to modify the batch size if I want to train for MS COCO.

**Comment by eng100200** [comment]
@ZP-Guo thanks for reply. I am also planning to train using mpii, but, i would do it for compact model, model have less than 8G flops....and also my target is to train for sixteen points only. Can i ask you one question, why the scale is multipled by 1.25 when center has positive value?
 if center[0] != -1:
            scale = scale * 1.25

**Comment by ZP-Guo** [comment]
> @ZP-Guo thanks for reply. I am also planning to train using mpii, but, i would do it for compact model, model have less than 8G flops....and also my target is to train for sixteen points only. Can i ask you one question, why the scale is multipled by 1.25 when center has positive value?
> if center[0] != -1:
> scale = scale * 1.25

So sorry I can not give you an answer because I do not pay much attention to code details.
I think the author  often set some value empirically, so I can not explain it. For example, HRNet is trained for face datasets. You know, HRNet can complete many tasks, such as human pose estimation and face detection. Someone asks a question how to get the "center" and "scale" values in an issue that comes from face detection task. And I find the author set a value "200" empirically. This issue is found by my friend and he told me when we chat so that I do not save it. What I want to say is that maybe he, the author sets some value empirically, not some reasons for calculation.
Maybe many problems that we can not solve come. But do not give up and we will do it. Come on, bro. 😎

**Comment by eng100200** [comment]
@ZP-Guo  i understand your answer...i would try to go deeper,,,and if i find answer i would share with you. However, i am using HRNET for pose estimation.

**Comment by ZP-Guo** [comment]
> @ZP-Guo i understand your answer...i would try to go deeper,,,and if i find answer i would share with you. However, i am using HRNET for pose estimation.

Maybe I understand CNN not enough. For example, why VGG-16 has 64, 128, 256 channels. I think the author set them empirically and I can not explain it via using calculation.
I also use CNN for human pose estimations, as you. And I will thank you for sharing if you would share what you find.

**Comment by eng100200** [comment]
@ZP-Guo  shake hands,,,,i think num of channels question is just a empricial choice....it could have many reasoning,,,like cost of memory,...computation.....enough information from these number of channels.....
do you have wechat?

**Comment by ZP-Guo** [comment]
> @ZP-Guo shake hands,,,,i think num of channels question is just a empricial choice....it could have many reasoning,,,like cost of memory,...computation.....enough information from these number of channels.....
> do you have wechat?

I mean why they choose 64, 128, 256, and so on. 128 = 64 * 2, 256 = 128 * 2. Why not it is 61, 122, 244 or 55, 110, 220. But it does not matter. Maybe it is okay that I know how to use it.
And we can exhange experience via e-mail. You can get the e-mail on my homepage. 😊

**Comment by eng100200** [comment]
@ZP-Guo @dzyjjpy  @alex-razor  have you recieved error "raise RuntimeError("Failed to export an ONNX attribute, "
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible" 
during training using mpii dataset? i have installed pytorch=1.1.0 and tensorboradX =1.6? should i upgrade tensorboardX?

**Comment by ZP-Guo** [comment]
> @ZP-Guo @dzyjjpy @alex-razor have you recieved error "raise RuntimeError("Failed to export an ONNX attribute, "
> RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible"
> during training using mpii dataset? i have installed pytorch=1.1.0 and tensorboradX =1.6? should i upgrade tensorboardX?

 So sorry, I have not met this bug. Maybe you can update your environment according to my version.

**Comment by 1037861070** [comment]
sorry could tell total version about this work, i want to run train coco dataSet  but always appear cpu_nms.py", line 12
    cimport numpy as np

**Comment by Muhtasham** [comment]
> @dzyjjpy hello, i want to ask few questions;
> 
> 1. Why we flipped images in testing the mpii dataset?
> 2. I think mpii provide bounding box, but, i am not sure. However, how did you get the bounding boxes for mpii and how you computed center and scale?
> 3. Further, the validation set of mpii used for testing do you single person detection or multi-person detection?
> 4. how can i display images after i detect the pose points, i mean disply with pose points?
> 5. how can i test any image of my own?

Hello, did you find answers for your questions? I'm also curious.

**Comment by eng100200** [comment]
@dzyjjpy  you mean flip for testing? part 2 to 5 i can answer your questions

**Comment by Muhtasham** [comment]
> @dzyjjpy you mean flip for testing? part 2 to 5 i can answer your questions

Can you please answer part 2 to 5

**Comment by yangsenius** [comment]
`None` in `nn.ModuleList` break the JIT in higher version of PyTorch. This problem is resolved by this issue. https://github.com/pytorch/pytorch/issues/30459.

**Comment by X-tan58** [comment]
![image](https://user-images.githubusercontent.com/95734189/166865360-a84efa5c-cb24-4a4a-beae-23a5508ab118.png)
@TeeboneTing hi ,thanks your method. I use torch=1.0.0, it worked. But this error was raised later. Have you met ?

**Comment by X-tan58** [comment]
This is not exactly a run error, but a post-install torch1.0 error, although the package was successfully installed as well. But I ran into this problem when I ran the code. So I wonder if the problem in the picture is related to the problem in the previous picture.
![image](https://user-images.githubusercontent.com/95734189/166865785-18ac3dca-997c-4d27-88d4-08c74f2cd6e3.png)
