### ISSUE TITLE
ModuleNotFoundError: nms.cpu_nms

### ISSUE THREAD

**Issue by vasukalariya** [leoxiaobin/deep-high-resolution-net.pytorch#104]
Showing module not found error in nms.py file, 'nms.cpu_nms' is not found.

Error found while executing :
python tools/test.py \ --cfg experiments/mpii/hrnet/w32_256x256_adam_lr1e-3.yaml \ TEST.MODEL_FILE models/pytorch/pose_mpii/pose_hrnet_w32_256x256.pth

command prompt:

Traceback (most recent call last):
  File "tools/test.py", line 31, in <module>
    import dataset
  File "C:\Users\vasuk\HRNets\deep-high-resolution-net.pytorch-master\tools\..\lib\dataset\__init__.py", line 12, in <module>
    from .coco import COCODataset as coco
  File "C:\Users\vasuk\HRNets\deep-high-resolution-net.pytorch-master\tools\..\lib\dataset\coco.py", line 22, in <module>
    from nms.nms import oks_nms
  File "C:\Users\vasuk\HRNets\deep-high-resolution-net.pytorch-master\tools\..\lib\nms\nms.py", line 13, in <module>
    from .cpu_nms import cpu_nms
ModuleNotFoundError: No module named 'nms.cpu_nms'

**Comment by HeathHose** [comment]
cd ${POSE_ROOT}/lib
make
