### ISSUE TITLE
 Is it an error in the json file? How do I modify it

### ISSUE THREAD

**Issue by ahanahaner** [leoxiaobin/deep-high-resolution-net.pytorch#105]
when i train on coco dataset ,  i meet this issus : json.decoder.JSONDecodeError. 

loading annotations into memory...
Traceback (most recent call last):
  File "tools/train.py", line 257, in <module>
    main()
  File "tools/train.py", line 174, in main
    normalize,
  File "/home/jinhan/HRnet/tools/../lib/dataset/coco.py", line 68, in __init__
    self.coco = COCO(self._get_ann_file_keypoint())
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
  File "/usr/local/anaconda3/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/anaconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 158128038 (char 158128037)

**Comment by Flami42** [comment]
Hi! I'm having the same error... Did you solve it? If yes, how?
