### ISSUE TITLE
cd ${POSE_ROOT}/lib  make?

### ISSUE THREAD

**Issue by angechen** [leoxiaobin/deep-high-resolution-net.pytorch#118]
What's wrong?Help!
![图片](https://user-images.githubusercontent.com/45162172/66122427-371da400-e612-11e9-84b6-dccd9a662ab7.png)

**Comment by angechen** [comment]
I solve it.
![图片](https://user-images.githubusercontent.com/45162172/66123257-24a46a00-e614-11e9-9b23-0240b2d84401.png)

**Comment by henbucuoshanghai** [comment]
but error like 
cd nms; python setup_linux.py build_ext --inplace; rm -rf build; cd ../../
Traceback (most recent call last):
  File "setup_linux.py", line 56, in <module>
    CUDA = locate_cuda()
  File "setup_linux.py", line 44, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME









hoow to slove it

**Comment by nwicakson** [comment]
@henbucuoshanghai  have you solved this? the nvcc
