### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__name__'

### ISSUE THREAD

**Issue by angechen** [leoxiaobin/deep-high-resolution-net.pytorch#119]
when i do: 
python tools/train.py \
    --cfg experiments/mpii/hrnet/w32_256x256_adam_lr1e-3.yaml
an error  occurrs:
![图片](https://user-images.githubusercontent.com/45162172/66205231-736b0600-e6df-11e9-94d8-71d515459b7e.png)

However,when i do:
python tools/test.py \
    --cfg experiments/mpii/hrnet/w32_256x256_adam_lr1e-3.yaml \
    TEST.MODEL_FILE models/pytorch/pose_mpii/pose_hrnet_w32_256x256.pth
there is nothing wrong.

**Comment by leoxiaobin** [comment]
could you provide the full error information for that?

**Comment by dzyjjpy** [comment]
I met the same issue, full error information shows as below:  @leoxiaobin @angechen 
WORKERS: 24
=> init weights from normal distribution
=> loading pretrained model models/pytorch/imagenet/hrnet_w32-36af842e.pth
Traceback (most recent call last):
  File "tools/train.py", line 223, in <module>
    main()
  File "tools/train.py", line 111, in main
    writer_dict['writer'].add_graph(model, (dump_input, ))
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/tensorboardX/writer.py", line 774, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 275, in graph
    trace = torch.jit.trace(model, args)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 632, in trace
    module = TopLevelTracedModule(func, **executor_options)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 950, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 950, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 1307, in __init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 950, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 1307, in __init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 950, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 1307, in __init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 950, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 1307, in __init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 950, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 1307, in __init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 950, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/jiapy/virtualEnv/py3torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 1282, in __init__
    self._name = orig.__name__
AttributeError: 'NoneType' object has no attribute '__name__'

**Comment by angechen** [comment]
I have solved it .Because the tensorboardX version is wrong. In the requirements.txt，the version of tensorboardX is>=1.6，however，when i installed the version 1.7,the above error occurs，so you should pip install tensorboardX==1.6

**Comment by dzyjjpy** [comment]
@angechen thanks for your reply. before that, I met another mistake, and I downgrade tensorboardX->1.6 before, but another issue displayed however.
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/issues/100 (#100 )
so I change torch's version (from 1.2 to 1.0), met the isssue above(#119)
I will have a try.

**Comment by dzyjjpy** [comment]
it works after downgrading tensorboardX to 1.6 (torch==1.0), thank you so much

**Comment by angechen** [comment]
You are welcome.May I ask which country you are from?




------------------ 原始邮件 ------------------
发件人: "jpy.cas"<notifications@github.com>; 
发送时间: 2019年10月12日(星期六) 上午9:31
收件人: "leoxiaobin/deep-high-resolution-net.pytorch"<deep-high-resolution-net.pytorch@noreply.github.com>; 
抄送: "剪个平头骄傲一生"<1094483015@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [leoxiaobin/deep-high-resolution-net.pytorch] AttributeError:'NoneType' object has no attribute '__name__' (#119)




it works after downgrading tensorboardX to 1.6 (torch==1.0), thank you so much

**Comment by dzyjjpy** [comment]
China

**Comment by angechen** [comment]
我也是中国人，哈哈，怪不得我觉得没啥时差。




------------------ 原始邮件 ------------------
发件人: "jpy.cas"<notifications@github.com>; 
发送时间: 2019年10月12日(星期六) 上午9:37
收件人: "leoxiaobin/deep-high-resolution"<deep-high-resolution-net.pytorch@noreply.github.com>; 
抄送: "剪个平头骄傲一生"<1094483015@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [leoxiaobin/deep-high-resolution-net.pytorch] AttributeError:'NoneType' object has no attribute '__name__' (#119)




China

**Comment by angechen** [comment]
你能装上opencv-python==3.4.1.15吗，这个版本好像装不上。




------------------ 原始邮件 ------------------
发件人: "jpy.cas"<notifications@github.com>; 
发送时间: 2019年10月12日(星期六) 上午9:31
收件人: "leoxiaobin/deep-high-resolution"<deep-high-resolution-net.pytorch@noreply.github.com>; 
抄送: "剪个平头骄傲一生"<1094483015@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [leoxiaobin/deep-high-resolution-net.pytorch] AttributeError:'NoneType' object has no attribute '__name__' (#119)




it works after downgrading tensorboardX to 1.6 (torch==1.0), thank you so much

**Comment by angechen** [comment]
Can you pip install opencv-python==3.4.1.15? This version can not be found ,so i pip install 3.4.2.17。
