### ISSUE TITLE
cd nms; python setup_linux.py build_ext --inplace; rm -rf build; cd ../../ Traceback (most recent call last):   File "setup_linux.py", line 56, in <module>     CUDA = locate_cuda()   File "setup_linux.py", line 44, in locate_cuda     raise EnvironmentError('The nvcc binary could not be ' OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME

### ISSUE THREAD

**Issue by henbucuoshanghai** [leoxiaobin/deep-high-resolution-net.pytorch#143]
Traceback (most recent call last):
  File "setup_linux.py", line 56, in <module>
    CUDA = locate_cuda()
  File "setup_linux.py", line 44, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME

**Comment by GuHuangAI** [comment]
i miss the same error. Could you please tell me how to solve it?

**Comment by GuHuangAI** [comment]
I solve the problem by reinstall CUDA10.0,hope its useful

**Comment by npduyduc** [comment]
You run it on Windows, right? It name's setup_lunux.py so I think it can run on Windows

**Comment by maxmarkov** [comment]
I encountered this problem as well. Here is the solution

Add the following lines to your ~/.bashrc (change the cuda version)

export CUDAHOME=/usr/local/cuda-10.0
export LD_LIBRARY_PATH=${CUDAHOME}/lib64
PATH=${CUDAHOME}/bin:${PATH}
export PATH

**Comment by NO11s** [comment]
I solved the problem. Here is the solution

$ sudo apt install nvidia-cuda-toolkit
