### ISSUE TITLE
ERROR using numpy with version >=1.18

### ISSUE THREAD

**Issue by hyczkg** [leoxiaobin/deep-high-resolution-net.pytorch#177]
an error appeared when I use  numpy 1.18 for this code:

Traceback (most recent call last):
  File "tools/train.py", line 210, in <module>
    main()
  File "tools/train.py", line 180, in main
    final_output_dir, tb_log_dir
  File "deep-high-resolution-net.pytorch/tools/../lib/core/function.py", line 200, in validate
    filenames, imgnums
  File "deep-high-resolution-net.pytorch/tools/../lib/dataset/coco.py", line 362, in evaluate
    res_file, res_folder)
  File "deep-high-resolution-net.pytorch/tools/../lib/dataset/coco.py", line 433, in _do_python_keypoint_eval
    coco_eval = COCOeval(self.coco, coco_dt, 'keypoints')
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/cocoeval.py", line 529, in __init__
    self.setKpParams()
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/cocoeval.py", line 518, in setKpParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

because linspace function is no more supported in 1.18.
after I uninstalled numpy 1.18 and installed numpy 1.17, it works well.

the code works well if the numpy version requirements.txt is fixed as numpy==1.17

**Comment by dzyjjpy** [comment]
I also met this issue for eval.py, try to reinstall 1.12. or 1.11, no work.
reinstall numpy==1.17, it works.
