### ISSUE TITLE
Import error : failed to map segment from shared object

### ISSUE THREAD

**Issue by riorafe** [leoxiaobin/deep-high-resolution-net.pytorch#194]
Hello, can anyone help me to fix this error?
I have made new fresh conda env and install pytorch 1.5.1 with cuda 10.2 
and follow every single step from requirements.txt and cocoapi
But I still get this error below

Traceback (most recent call last):
  File "tools/test.py", line 31, in <module>
    import dataset
  File "/mnt/sdb5/deep-high-resolution-net.pytorch/tools/../lib/dataset/__init__.py", line 12, in <module>
    from .coco import COCODataset as coco
  File "/mnt/sdb5/deep-high-resolution-net.pytorch/tools/../lib/dataset/coco.py", line 22, in <module>
    from nms.nms import oks_nms
  File "/mnt/sdb5/deep-high-resolution-net.pytorch/tools/../lib/nms/nms.py", line 13, in <module>
    from .cpu_nms import cpu_nms
ImportError: /mnt/sdb5/deep-high-resolution-net.pytorch/tools/../lib/nms/cpu_nms.cpython-38-x86_64-linux-gnu.so: failed to map segment from shared object

**Comment by riorafe** [comment]
I have found that 
`cd lib`
`make `
didn't run successfully
![clipboard-image](https://user-images.githubusercontent.com/46643712/86388532-285a3f80-bcbf-11ea-8d92-859ec1b0cc72.png)
then i did 
`sudo make`
![image](https://user-images.githubusercontent.com/46643712/86388730-766f4300-bcbf-11ea-809a-340670b46c52.png)
and got error above
I have installed cython both using pip and conda
first install using pip then uninstall and then using conda
I use the latest version of cython

**cython                    0.29.20          py38he6710b0_0    anaconda**

then i found out in documentation that 
`Cython.Disutils.Build_ext` isn't available anymore
![clipboard-image (1)](https://user-images.githubusercontent.com/46643712/86388995-e1207e80-bcbf-11ea-8d3b-b5b03e095995.png)

I wonder what version of cython do u guys install in order to successfully run 'make'

**Comment by zhangrj91** [comment]
Have you solved this problem?
