### ISSUE TITLE
AssertionError: Invalid device id

### ISSUE THREAD

**Issue by ankitgc1** [leoxiaobin/deep-high-resolution-net.pytorch#27]

**Comment by tianjiahao** [comment]
1.change the code in test.py:
model = torch.nn.DataParallel(model,device_ids=cfg.GPUS).cuda() to
model = torch.nn.DataParallel(model, device_ids=(0,)).cuda()

**Comment by YinRui1991** [comment]
I use 
model = torch.nn.DataParallel(model, device_ids=[0]).cuda()

**Comment by rrbarioni** [comment]
Instead of directly changing test.py code at `model = torch.nn.DataParallel(model,device_ids=cfg.GPUS).cuda()`,

**Comment by Malithi-gif** [comment]
warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "gtad_train.py", line 109, in <module>
    model = torch.nn.DataParallel(model, device_ids=list(range(opt['n_gpu']))).cuda()
  File "/usr/local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 136, in __init__
    _check_balance(self.device_ids)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 19, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/usr/local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 19, in <listcomp>
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 317, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id

I face the same problem, I work at google colab. cuda 10.1

**Comment by Malithi-gif** [comment]
> 1.change the code in test.py:
> model = torch.nn.DataParallel(model,device_ids=cfg.GPUS).cuda() to
> model = torch.nn.DataParallel(model, device_ids=(0,)).cuda()

where the test.py located?

**Comment by Shadowwalker10** [comment]
> Instead of directly changing test.py code at
> `model = torch.nn.DataParallel(model,device_ids=cfg.GPUS).cuda()`,
> You can execute test.py by giving the list of gpus as a parameter. Example:
> `python tools/test.py --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml TEST.MODEL_FILE models/pytorch/pose_coco/pose_hrnet_w32_256x192.pth GPUS (0,)`

But using GPUS(0,) throws syntax error near unexpected token `('....please help

**Comment by gulraizk94** [comment]
@Shadowwalker10  
Please use GPUS [0]. I hope it would resolve issue for you.

**Comment by ChloeS31** [comment]
instead of 
!python tools/train.py --cfg experiments/mpii/hrnet/w32_256x256_adam_lr1e-3.yaml, which gives and error like above mentioned from others,
I've used 
!python tools/train.py --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml TEST.MODEL_FILE models/pytorch/pose_coco/pose_hrnet_w32_256x192.pth GPUS [0]
and it seems like it's working so far, but what does TEST.MODEL_FILE models/pytorch/pose_coco/pose_hrnet_w32_256x192.pth GPUS [0] do exactly?
