### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'reduction'

### ISSUE THREAD

**Issue by LouisNUST** [leoxiaobin/deep-high-resolution-net.pytorch#80]
Traceback (most recent call last):
  File "tools/test.py", line 130, in <module>
    main()
  File "tools/test.py", line 102, in main
    use_target_weight=cfg.LOSS.USE_TARGET_WEIGHT
  File "/home/louis/Documents/DetPose/HRNet/HRPose/tools/../lib/core/loss.py", line 18, in __init__
    self.criterion = nn.MSELoss(reduction='mean')
TypeError: __init__() got an unexpected keyword argument 'reduction'

pytorch=0.4.1
cudatoolkit=10.0

**Comment by LouisNUST** [comment]
change the pytorch=1.0.0, the TypeError is the same. why?

**Comment by 2429581027** [comment]
Hello, I have the same mistake. Can you solve it? Can you tell me your method?

**Comment by gaoyao123** [comment]
I have deleted 'reduction=mean' and no problems.

**Comment by YHDang** [comment]
Please replace the `(reduction='mean')` with `(reduce=True, size_average=True)`.
