### ISSUE TITLE
AttributeError: module 'torch.onnx.utils' has no attribute 'OperatorExportTypes'

### ISSUE THREAD

**Issue by LouisNUST** [leoxiaobin/deep-high-resolution-net.pytorch#81]
Traceback (most recent call last):
  File "tools/train.py", line 223, in <module>
    main()
  File "tools/train.py", line 111, in main
    writer_dict['writer'].add_graph(model, (dump_input, ))
  File "/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/tensorboardX/writer.py", line 697, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 305, in graph
    operator_export_type = torch.onnx.utils.OperatorExportTypes.ONNX
AttributeError: module 'torch.onnx.utils' has no attribute 'OperatorExportTypes'

pytorch=0.4.1
cudatoolkit=10.0

**Comment by azuryl** [comment]
same problem

**Comment by Aliiiu** [comment]
pls share if you were able to solve this

**Comment by Lopa07** [comment]
I am seeing the same error. Apparently the newer version of ONNX does not have these files. Can you please share the torch version used? That will help to narrow down the ONNX version as well.

**Comment by Lopa07** [comment]
Updating requirements.txt, as shown below, solved my issue.
```
EasyDict==1.7
opencv-python==3.4.8.29
shapely==1.6.4
Cython
scipy
pandas
pyyaml
json_tricks
scikit-image
yacs>=0.1.5
tensorboardX
tensorboard
torch
torchvision
numpy==1.20
```
