### ISSUE TITLE
writer error

### ISSUE THREAD

**Issue by ooFormalinoo** [leoxiaobin/deep-high-resolution-net.pytorch#98]
there are some errors when i am training. It's seems because of tensorboardX.However, I have installed lastest tensorboardX with the command pip install tensorboardX. 

=> init weights from normal distribution
=> loading pretrained model models/pytorch/imagenet/hrnet_w32-36af842e.pth
Traceback (most recent call last):
  File "tools/train.py", line 223, in <module>
    main()
  File "tools/train.py", line 111, in main
    writer_dict['writer'].add_graph(model, (dump_input, ))
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/tensorboardX/writer.py", line 738, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/tensorboardX/pytorch_graph.py", line 240, in graph
    trace = torch.jit.trace(model, args)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 772, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 898, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 669, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1881, in __init__
    self._modules[name] = TracedModule(submodule, id_set)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1881, in __init__
    self._modules[name] = TracedModule(submodule, id_set)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1881, in __init__
    self._modules[name] = TracedModule(submodule, id_set)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1881, in __init__
    self._modules[name] = TracedModule(submodule, id_set)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1881, in __init__
    self._modules[name] = TracedModule(submodule, id_set)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/kjq/.conda/envs/hrnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1855, in __init__
    assert(isinstance(orig, torch.nn.Module))
AssertionError

**Comment by ahanahaner** [comment]
I have the same problem as you. Have you solved it？

**Comment by ooFormalinoo** [comment]
> I have the same problem as you. Have you solved it？

I solved it by changing the tensorboardX version. it seems okay with pytorch1.0 and tensorboardX1.6

**Comment by ahanahaner** [comment]
Thank you very much for your reply. I will try it .




------------------ 原始邮件 ------------------
发件人: "ooFormalinoo"<notifications@github.com>;
发送时间: 2019年8月27日(星期二) 下午5:55
收件人: "leoxiaobin/deep-high-resolution-net.pytorch"<deep-high-resolution-net.pytorch@noreply.github.com>;
抄送: "Han.er"<626294451@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [leoxiaobin/deep-high-resolution-net.pytorch] writer error (#98)



 
I have the same problem as you. Have you solved it？
  
I solved it by changing the tensorboardX version. it seems okay with pytorch1.0 and tensorboardX1.6

**Comment by ahanahaner** [comment]
Thank you very much for your reply.

**Comment by YibinXie97** [comment]
I encountered this problem when I run this code. Then I switched my torch vision from 1.2.0 to 1.0.0 and torchvision 0.4.0 0.2.0. TensorboardX stays the version of 1.6.0 as the author requires. Then the problem solved. So I think this is because of the incompatible versions between tensorboardX and pytorch. 
`writer_dict['writer'].add_graph(model, (dump_input, ))`
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/blob/015c946696abe02749f90b33a27f63652ea06a16/tools/train.py#L111

**Comment by Muhtasham** [comment]
@YibinXie97  i did like you said but having the error below, can you please help? 
should i comment **writer_dict['writer'].add_graph(model, (dump_input, ))**  ? 

> File "tools/train.py", line 223, in <module>
>     main()
>   File "tools/train.py", line 115, in main
>     model = torch.nn.DataParallel(model, device_ids=cfg.GPUS).cuda()
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 131, in __init__
>     _check_balance(self.device_ids)
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 18, in _check_balance
>     dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 18, in <listcomp>
>     dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
>   File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 301, in get_device_properties
>     raise AssertionError("Invalid device id")
> AssertionError: Invalid device id

i'm working on google colab

**Comment by U-C-J** [comment]
Hello I met same error message. I have tried many ways and met other bugs also.  I finally make it to run by doing the following. I am new to linux. If you find anything not right, please let me know.

1. check cuda version and environment variable setting. 
    open lib\nms\linux_setup.py, check whether cuda and nvcc works right.
   (1) os.environ['CUDAHOME'] 
   (2)  nvcc = pjoin(home, 'bin', 'nvcc') which means you should have nvcc under %CUDAHOME%\bin

2. use the following version:
    pytorch== 1.0.1
    torchvision==0.2.2
    tensorboardX==1.6
    Pillow==5.2.0 

Now I have tried the testing and training code for MPII. It seems it is running right.
